import { randomUUID } from 'node:crypto';
import { WebSocketServer, WebSocket } from 'ws';

type Role = 'host' | 'participant' | 'tv';
type Client = { socket: WebSocket; sessionId: string; participantId: string; role: Role };
type Message = { type?: string; sessionId?: string; senderId?: string; payload?: any };
type Session = { sessionId: string; hostParticipantId: string; state: any; clients: Map<string, Client>; sequence: number; timer?: ReturnType<typeof setTimeout>; cleanup?: ReturnType<typeof setTimeout> };

type EventType = 'participant.joined' | 'participant.left' | 'participant.updated' | 'host.changed' | 'queue.added' | 'queue.updated' | 'queue.removed' | 'queue.next' | 'singer.called' | 'performance.started' | 'performance.paused' | 'performance.resumed' | 'performance.finished' | 'performance.scored' | 'round.updated' | 'session.settings.changed';

const port = Number(process.env.PORT ?? 8787);
const capacityDefault = clamp(Number(process.env.DEFAULT_SESSION_CAPACITY ?? 50), 2, 100);
const songsPerParticipant = clamp(Number(process.env.MAX_SONGS_PER_PARTICIPANT ?? 3), 1, 20);
const legacySnapshots = process.env.LEGACY_SNAPSHOT_BROADCAST !== 'false';
const sessions = new Map<string, Session>();
const clients = new Map<WebSocket, Client>();

function clamp(value: number, min: number, max: number): number { return Number.isFinite(value) ? Math.max(min, Math.min(max, Math.floor(value))) : min; }
function validId(value: unknown): value is string { return typeof value === 'string' && value.trim().length > 0 && value.length <= 128; }
function send(socket: WebSocket, type: string, payload: unknown): void { if (socket.readyState === WebSocket.OPEN) socket.send(JSON.stringify({ id: randomUUID(), type, timestamp: Date.now(), payload })); }
function error(socket: WebSocket, message: string): void { send(socket, 'session.error', { message }); }
function broadcast(s: Session, type: string, payload: unknown, except?: string): void { for (const c of s.clients.values()) if (c.participantId !== except) send(c.socket, type, payload); }
function participant(s: Session, id: string): any | undefined { return s.state.participants.find((p: any) => p.id === id); }
function activeCount(s: Session): number { return s.state.participants.filter((p: any) => p.role !== 'tv' && p.online !== false).length; }
function emit(s: Session, type: EventType, payload: unknown, actor?: string, audience?: string[]): void { const e = { eventId: randomUUID(), sequence: ++s.sequence, sessionId: s.sessionId, type, timestamp: Date.now(), ...(actor ? { actorParticipantId: actor } : {}), ...(audience ? { audience: { participantIds: audience } } : {}), payload }; for (const c of s.clients.values()) if (!audience || audience.includes(c.participantId)) send(c.socket, 'session.event', e); }
function changed(s: Session, type: EventType, payload: unknown, actor?: string, audience?: string[]): void { s.state.queueSize = Array.isArray(s.state.queue) ? s.state.queue.length : 0; emit(s, type, payload, actor, audience); if (legacySnapshots) broadcast(s, 'session.state', { state: s.state }); }
function ensureState(state: any, sessionId: string, hostId: string): any { const s = state && typeof state === 'object' ? state : {}; s.sessionId = sessionId; s.hostParticipantId = hostId; s.createdAt ??= Date.now(); s.maxParticipants = clamp(Number(s.maxParticipants ?? capacityDefault), 2, 100); s.participants = Array.isArray(s.participants) ? s.participants : []; s.queue = Array.isArray(s.queue) ? s.queue : []; s.queueSize = s.queue.length; s.roundId ??= randomUUID(); s.roundMode ??= { kind: 'songs', songCount: 1 }; s.roundResultsByParticipant ??= {}; s.restartCreditsByParticipant ??= {}; s.autoAdvance ??= true; s.status ??= 'lobby'; return s; }
function credits(mode: any): number { if (mode?.kind === 'open') return 1; const n = clamp(Number(mode?.songCount ?? 1), 1, 100); return n <= 2 ? 1 : n <= 4 ? 2 : Math.max(1, Math.floor(n * 0.3)); }
function ensureCredits(s: Session, id: string): void { s.state.restartCreditsByParticipant[id] ??= credits(s.state.roundMode); }
function position(q: any): number { if (q.playbackState === 'paused') return Math.max(0, Number(q.playbackPositionSeconds ?? 0)); if (Number.isFinite(q.playbackStartedAt)) return Math.max(0, (Date.now() - Number(q.playbackStartedAt)) / 1000); return Math.max(0, Number(q.playbackPositionSeconds ?? 0)); }
function fairNext(s: Session): any | undefined { if (s.state.queue.some((q: any) => q.status === 'playing')) return undefined; const list = s.state.queue.filter((q: any) => { if (q.status !== 'ready') return false; const p = participant(s, q.ownerParticipantId); if (!p || p.online === false || p.role === 'tv') return false; const r = s.state.roundResultsByParticipant?.[q.ownerParticipantId]; return !(s.state.roundMode?.kind === 'songs' && r?.roundId === s.state.roundId && r.finished); }); list.sort((a: any, b: any) => { const ac = Number(s.state.roundResultsByParticipant?.[a.ownerParticipantId]?.completedSongs ?? 0); const bc = Number(s.state.roundResultsByParticipant?.[b.ownerParticipantId]?.completedSongs ?? 0); if (ac !== bc) return ac - bc; const aq = s.state.queue.filter((x: any) => x.ownerParticipantId === a.ownerParticipantId && !['completed','cancelled'].includes(x.status)).length; const bq = s.state.queue.filter((x: any) => x.ownerParticipantId === b.ownerParticipantId && !['completed','cancelled'].includes(x.status)).length; return aq - bq || Number(a.addedAt) - Number(b.addedAt); }); return list[0]; }
function start(s: Session, q: any): void { const now = Date.now(); const performanceId = `${q.id}-${now}-${randomUUID().slice(0,8)}`; const attempts = Array.isArray(q.attempts) ? [...q.attempts] : []; attempts.push({ performanceId, startedAt: now, cancelled: false, official: false }); s.state.queue = s.state.queue.map((x: any) => x.id === q.id ? { ...x, status: 'playing', roundId: s.state.roundId, playbackStartedAt: now, playbackPositionSeconds: 0, playbackState: 'playing', activePerformanceId: performanceId, attempts } : x); s.state.status = 'playing'; changed(s, 'queue.next', { queueEntryId: q.id, participantId: q.ownerParticipantId }, q.ownerParticipantId); emit(s, 'singer.called', { queueEntryId: q.id, participantId: q.ownerParticipantId }, q.ownerParticipantId); emit(s, 'performance.started', { queueEntryId: q.id, performanceId }, q.ownerParticipantId, [q.ownerParticipantId, ...s.state.participants.filter((p: any) => p.role === 'tv').map((p: any) => p.id)]); }
function schedule(s: Session): void { if (s.timer) clearTimeout(s.timer); s.timer = setTimeout(() => { s.timer = undefined; if (s.state.autoAdvance === false || s.state.status === 'finished') return; if (s.state.queue.some((q: any) => q.status === 'playing')) return; const q = fairNext(s); if (q) start(s, q); }, 2500); }
function roundDone(s: Session): boolean { if (s.state.roundMode?.kind !== 'songs') return false; const owners: string[] = Array.from(new Set<string>(s.state.queue.filter((q: any) => q.roundId === s.state.roundId).map((q: any) => q.ownerParticipantId))); return owners.length > 0 && !s.state.queue.some((q: any) => q.status === 'playing') && owners.every((id: string) => s.state.roundResultsByParticipant?.[id]?.roundId === s.state.roundId && s.state.roundResultsByParticipant[id].finished); }

const wss = new WebSocketServer({ port });
wss.on('connection', socket => {
  socket.on('message', raw => {
    let m: Message; try { m = JSON.parse(raw.toString()); } catch { error(socket, 'Mensagem JSON inválida.'); return; }
    if (m.type === 'session.create') {
      if (!validId(m.sessionId) || !validId(m.senderId)) return error(socket, 'sessionId e senderId são obrigatórios.');
      if (sessions.has(m.sessionId)) return error(socket, 'A sessão já existe.');
      const state = ensureState(m.payload?.state, m.sessionId, m.senderId); const host = state.participants.find((p: any) => p.id === m.senderId); if (host) { host.role = 'host'; host.online = true; } else state.participants.unshift({ id: m.senderId, name: String(m.payload?.name ?? 'Host').slice(0,30), role:'host', joinedAt:Date.now(), capabilities:m.payload?.capabilities ?? {}, online:true }); ensureCredits({ state } as Session, m.senderId);
      const s: Session = { sessionId:m.sessionId, hostParticipantId:m.senderId, state, clients:new Map(), sequence:0 }; const c: Client = { socket, sessionId:m.sessionId, participantId:m.senderId, role:'host' }; s.clients.set(c.participantId,c); clients.set(socket,c); sessions.set(s.sessionId,s); send(socket,'session.created',{ sessionId:s.sessionId, hostParticipantId:s.hostParticipantId, state:s.state }); return;
    }
    if (!validId(m.sessionId) || !validId(m.senderId)) return error(socket, 'sessionId e senderId são obrigatórios.');
    if (m.type === 'session.join') {
      const s=sessions.get(m.sessionId); if(!s) return error(socket,'Sessão não encontrada.'); const role:Role=m.payload?.role==='tv'?'tv':'participant'; if(role!=='tv'&&activeCount(s)>=s.state.maxParticipants)return error(socket,'A sessão atingiu a capacidade de participantes.'); if(s.clients.has(m.senderId))return error(socket,'Este participante já está conectado.'); const old=participant(s,m.senderId); if(old&&old.online!==false)return error(socket,'Este participante já está ativo nesta sessão.'); if(old){old.online=true;old.role=role;}else s.state.participants.push({id:m.senderId,name:String(m.payload?.name??'Participante').slice(0,30),role,joinedAt:Date.now(),capabilities:m.payload?.capabilities??{},online:true}); if(role!=='tv')ensureCredits(s,m.senderId); const c:Client={socket,sessionId:m.sessionId,participantId:m.senderId,role};s.clients.set(c.participantId,c);clients.set(socket,c);changed(s,'participant.joined',{participant:participant(s,m.senderId),participantCount:activeCount(s)},m.senderId);send(socket,'session.joined',{sessionId:s.sessionId,hostParticipantId:s.hostParticipantId,state:s.state});return;
    }
    if (m.type === 'session.reconnect') {
      const s=sessions.get(m.sessionId);if(!s)return error(socket,'Sessão não encontrada ou expirada.');const p=participant(s,m.senderId);if(!p)return error(socket,'Participante não encontrado nesta sessão.');const old=s.clients.get(m.senderId);if(old?.socket!==socket){try{old?.socket.close();}catch{}s.clients.delete(m.senderId);}if(s.cleanup){clearTimeout(s.cleanup);s.cleanup=undefined;}p.online=true;const c:Client={socket,sessionId:m.sessionId,participantId:m.senderId,role:p.role};s.clients.set(c.participantId,c);clients.set(socket,c);send(socket,'session.reconnected',{sessionId:s.sessionId,hostParticipantId:s.hostParticipantId,state:s.state});changed(s,'participant.updated',{participant:p},m.senderId);return;
    }
    const c=clients.get(socket);if(!c)return error(socket,'Conecte-se a uma sessão primeiro.');const s=sessions.get(c.sessionId);if(!s)return error(socket,'Sessão não encontrada.');const st=s.state;
    switch(m.type){
      case 'queue.add':{if(c.role==='tv')return error(socket,'A TV não pode adicionar músicas.');const count=st.queue.filter((q:any)=>q.ownerParticipantId===c.participantId&&!['completed','cancelled'].includes(q.status)).length;if(count>=songsPerParticipant)return error(socket,`Você atingiu o limite de ${songsPerParticipant} músicas na fila.`);const title=String(m.payload?.title??'').trim().slice(0,160);if(!title)return error(socket,'O título da música é obrigatório.');const q={id:randomUUID(),ownerParticipantId:c.participantId,title,artist:String(m.payload?.artist??'').trim().slice(0,120)||undefined,sourceId:String(m.payload?.sourceId??'').trim().slice(0,200)||undefined,source:String(m.payload?.source??'').trim().slice(0,80)||undefined,sourceUrl:String(m.payload?.sourceUrl??'').trim().slice(0,1000)||undefined,thumbnailUrl:String(m.payload?.thumbnailUrl??'').trim().slice(0,2000)||undefined,requestedKey:String(m.payload?.requestedKey??'').trim().slice(0,8)||undefined,durationSeconds:Number.isFinite(m.payload?.durationSeconds)?Math.max(0,Math.min(3600,Number(m.payload.durationSeconds))):undefined,roundId:st.roundId,addedAt:Date.now(),status:'queued'};st.queue.push(q);changed(s,'queue.added',{entry:q},c.participantId);break;}
      case 'queue.remove':{const id=String(m.payload?.queueEntryId??'');const q=st.queue.find((x:any)=>x.id===id);if(!q)return error(socket,'Música não encontrada na fila.');if(c.participantId!==s.hostParticipantId&&q.ownerParticipantId!==c.participantId)return error(socket,'Você só pode remover suas próprias músicas.');if(q.status==='playing')return error(socket,'Finalize ou pule a música antes de removê-la.');st.queue=st.queue.filter((x:any)=>x.id!==id);changed(s,'queue.removed',{queueEntryId:id},c.participantId);break;}
      case 'queue.status.set':{const id=String(m.payload?.queueEntryId??'');const q=st.queue.find((x:any)=>x.id===id);const status=String(m.payload?.status??'');if(!q)return error(socket,'Música não encontrada na fila.');if(!['queued','preparing','ready','playing','completed','cancelled'].includes(status))return error(socket,'Status de fila inválido.');const ownerCan=q.ownerParticipantId===c.participantId&&!['playing','completed'].includes(status);if(c.participantId!==s.hostParticipantId&&!ownerCan)return error(socket,'Somente o Host pode iniciar/finalizar a apresentação; o cantor pode preparar a própria música.');if(status==='playing'){if(st.queue.some((x:any)=>x.status==='playing'&&x.id!==id))return error(socket,'Já existe outra música em reprodução.');start(s,q);}else{st.queue=st.queue.map((x:any)=>x.id===id?{...x,status,...(m.payload?.assetId?{assetId:String(m.payload.assetId).slice(0,128)}:{}),...(m.payload?.manifestUrl?{manifestUrl:String(m.payload.manifestUrl).slice(0,2000)}:{}),...(m.payload?.originalKey?{originalKey:String(m.payload.originalKey).slice(0,16)}:{}),...(m.payload?.selectedKey?{selectedKey:String(m.payload.selectedKey).slice(0,8)}:{}),...(m.payload?.preparationStage?{preparationStage:String(m.payload.preparationStage).slice(0,40)}:{}),...(Number.isFinite(m.payload?.preparationProgress)?{preparationProgress:Math.max(0,Math.min(100,Number(m.payload.preparationProgress)))}:{}),...(m.payload?.preparationMessage?{preparationMessage:String(m.payload.preparationMessage).slice(0,200)}:{}),...(Number.isFinite(m.payload?.durationSeconds)?{durationSeconds:Math.max(0,Math.min(3600,Number(m.payload.durationSeconds)))}):x);changed(s,'queue.updated',{entry:st.queue.find((x:any)=>x.id===id),queueEntryId:id},c.participantId);}break;}
      case 'queue.next':{if(c.participantId!==s.hostParticipantId)return error(socket,'Somente o Host pode avançar a fila.');const q=fairNext(s);if(!q)return error(socket,'Não há música pronta e elegível para o próximo cantor.');start(s,q);break;}
      case 'queue.restart':{const id=String(m.payload?.queueEntryId??'');const q=st.queue.find((x:any)=>x.id===id);if(!q||q.ownerParticipantId!==c.participantId||q.status!=='playing')return error(socket,'Só o cantor pode recomeçar a própria apresentação em execução.');if(q.activePerformanceId!==String(m.payload?.performanceId??''))return error(socket,'Esta tentativa não é mais a tentativa ativa.');if(!Number.isFinite(q.durationSeconds)||!Number.isFinite(q.playbackStartedAt))return error(socket,'A duração da música não está disponível para validar o limite de 50%.');if(position(q)/Number(q.durationSeconds)*100>50)return error(socket,'O recomeço só pode ser usado até 50% da música.');const credit=Number(st.restartCreditsByParticipant?.[c.participantId]??0);if(credit<=0)return error(socket,'Você não possui mais créditos de recomeço nesta rodada.');st.restartCreditsByParticipant[c.participantId]=credit-1;const now=Date.now();const pid=`${id}-${now}-${randomUUID().slice(0,8)}`;const attempts=Array.isArray(q.attempts)?[...q.attempts]:[];const ai=attempts.findIndex((a:any)=>a.performanceId===q.activePerformanceId);if(ai>=0)attempts[ai]={...attempts[ai],endedAt:now,cancelled:true,cancelReason:'restart'};attempts.push({performanceId:pid,startedAt:now,cancelled:false,official:false});st.queue=st.queue.map((x:any)=>x.id===id?{...x,playbackStartedAt:now,playbackPositionSeconds:0,playbackState:'playing',activePerformanceId:pid,attempts,score:undefined}:x);changed(s,'performance.started',{queueEntryId:id,performanceId:pid},c.participantId);break;}
      case 'playback.control':{if(c.participantId!==s.hostParticipantId)return error(socket,'Somente o Host pode controlar a reprodução.');const action=String(m.payload?.action??'');const q=st.queue.find((x:any)=>x.id===String(m.payload?.queueEntryId??'')||x.status==='playing');if(!['pause','resume','skip','end'].includes(action))return error(socket,'Comando de reprodução inválido.');if(!q&&action!=='end')return error(socket,'Nenhuma música em reprodução.');if(action==='pause'){st.queue=st.queue.map((x:any)=>x.id===q.id?{...x,playbackPositionSeconds:position(q),playbackPausedAt:Date.now(),playbackState:'paused'}:x);changed(s,'performance.paused',{queueEntryId:q.id});}else if(action==='resume'){const pos=position(q);st.queue=st.queue.map((x:any)=>x.id===q.id?{...x,playbackStartedAt:Date.now()-Math.round(pos*1000),playbackState:'playing',playbackPausedAt:undefined}:x);changed(s,'performance.resumed',{queueEntryId:q.id});}else{st.queue=st.queue.map((x:any)=>x.id===q?.id?{...x,status:'cancelled',playbackState:undefined,playbackPositionSeconds:undefined,playbackPausedAt:undefined}:x);changed(s,'performance.finished',{queueEntryId:q?.id});if(action==='skip'&&st.autoAdvance!==false){const n=fairNext(s);if(n)start(s,n);}if(action==='end')st.status='finished';}break;}
      case 'playback.finished':{if(c.role!=='tv')return error(socket,'Somente a TV pode informar o fim automático da reprodução.');const id=String(m.payload?.queueEntryId??'');const q=st.queue.find((x:any)=>x.id===id);if(!q||q.status!=='playing'||q.playbackState==='paused')return;if(Number.isFinite(q.durationSeconds)&&position(q)+0.5<Number(q.durationSeconds))return error(socket,'A reprodução ainda não chegou ao final.');st.queue=st.queue.map((x:any)=>x.id===id?{...x,status:'completed',playbackState:undefined,playbackPositionSeconds:undefined,playbackPausedAt:undefined}:x);changed(s,'performance.finished',{queueEntryId:id});break;}
      case 'performance.complete':{const id=String(m.payload?.queueEntryId??'');const q=st.queue.find((x:any)=>x.id===id);const pid=String(m.payload?.performanceId??'');if(!q||q.ownerParticipantId!==c.participantId||q.status!=='completed'||q.activePerformanceId!==pid)return error(socket,'A apresentação não pode receber esta pontuação.');const raw=m.payload?.score??{};const score:any={};for(const k of ['overall','pitch','precision','rhythm','stability'])score[k]=Number.isFinite(raw[k])?Math.max(0,Math.min(100,Math.round(Number(raw[k])))):null;score.matchedSamples=Number.isFinite(raw.matchedSamples)?Math.max(0,Math.floor(Number(raw.matchedSamples))):null;if(Object.values(score).some((v:any)=>v===null))return error(socket,'Pontuação de apresentação inválida.');score.performanceId=pid;score.sealedAt=Date.now();st.queue=st.queue.map((x:any)=>x.id===id?{...x,score}:x);const scores=st.queue.filter((x:any)=>x.ownerParticipantId===q.ownerParticipantId&&x.roundId===st.roundId&&x.status==='completed'&&x.score).map((x:any)=>({queueEntryId:x.id,score:x.score.overall}));const required=st.roundMode?.kind==='songs'?Number(st.roundMode.songCount):undefined;const average=scores.length?Math.round(scores.reduce((sum:number,x:any)=>sum+x.score,0)/scores.length):undefined;st.roundResultsByParticipant[q.ownerParticipantId]={roundId:st.roundId,completedSongs:scores.length,...(required?{requiredSongs:required}:{}),...(average!==undefined?{score:average}:{}),finished:required?scores.length>=required:false,updatedAt:Date.now(),songScores:scores};changed(s,'performance.scored',{queueEntryId:id,performanceId:pid,score},c.participantId);if(roundDone(s)){st.status='finished';changed(s,'round.updated',{state:{status:st.status,roundResultsByParticipant:st.roundResultsByParticipant}});}else if(st.autoAdvance!==false)schedule(s);break;}
      case 'round.configure':{if(c.participantId!==s.hostParticipantId)return error(socket,'Somente o Host pode configurar a rodada.');const mode=m.payload?.mode;if(!mode||(mode.kind!=='open'&&mode.kind!=='songs')||(mode.kind==='songs'&&(!Number.isFinite(mode.songCount)||mode.songCount<1||mode.songCount>100)))return error(socket,'Modo de rodada inválido.');if(st.queue.some((q:any)=>q.status==='playing'))return error(socket,'Finalize a apresentação atual antes de configurar uma nova rodada.');st.roundId=randomUUID();st.roundMode=mode.kind==='open'?{kind:'open'}:{kind:'songs',songCount:Math.floor(mode.songCount)};st.roundResultsByParticipant={};st.restartCreditsByParticipant={};st.status='lobby';for(const p of st.participants)if(p.role!=='tv')st.restartCreditsByParticipant[p.id]=credits(st.roundMode);changed(s,'round.updated',{state:{roundId:st.roundId,roundMode:st.roundMode,roundResultsByParticipant:st.roundResultsByParticipant,restartCreditsByParticipant:st.restartCreditsByParticipant,status:st.status}},c.participantId);break;}
      case 'host.claim':{if(c.participantId===s.hostParticipantId)return;const old=participant(s,s.hostParticipantId);if(old?.online!==false)return error(socket,'O Host atual ainda está conectado.');if(c.role==='tv')return error(socket,'A TV não pode assumir o Host.');const previous=s.hostParticipantId;s.hostParticipantId=c.participantId;c.role='host';const oldClient=s.clients.get(previous);if(oldClient)oldClient.role='participant';st.hostParticipantId=c.participantId;st.participants=st.participants.map((p:any)=>p.id===previous?{...p,role:'participant'}:p.id===c.participantId?{...p,role:'host'}:p);changed(s,'host.changed',{previousHostParticipantId:previous,hostParticipantId:c.participantId,state:{hostParticipantId:st.hostParticipantId,participants:st.participants}},c.participantId);break;}
      case 'host.transfer':{if(c.participantId!==s.hostParticipantId)return error(socket,'Somente o Host atual pode transferir a função de Host.');const id=String(m.payload?.targetParticipantId??'');const target=participant(s,id);if(!target||target.role==='tv'||target.online===false)return error(socket,'O participante escolhido não pode assumir o Host.');const previous=s.hostParticipantId;s.hostParticipantId=id;const pc=s.clients.get(previous);const tc=s.clients.get(id);if(pc)pc.role='participant';if(tc)tc.role='host';st.hostParticipantId=id;st.participants=st.participants.map((p:any)=>p.id===previous?{...p,role:'participant'}:p.id===id?{...p,role:'host'}:p);changed(s,'host.changed',{previousHostParticipantId:previous,hostParticipantId:id,state:{hostParticipantId:st.hostParticipantId,participants:st.participants}},c.participantId);break;}
      case 'session.settings.set':{if(c.participantId!==s.hostParticipantId)return error(socket,'Somente o Host pode alterar as configurações da sessão.');const next= m.payload?.maxParticipants===undefined?st.maxParticipants:clamp(Number(m.payload.maxParticipants),2,100);if(next<activeCount(s))return error(socket,'A capacidade não pode ser menor que o número atual de participantes.');if(typeof m.payload?.autoAdvance==='boolean')st.autoAdvance=m.payload.autoAdvance;st.maxParticipants=next;changed(s,'session.settings.changed',{state:{autoAdvance:st.autoAdvance,maxParticipants:st.maxParticipants}},c.participantId);break;}
      case 'session.state.request':send(socket,'session.state',{state:st});break;
      case 'session.state.set':if(c.participantId!==s.hostParticipantId)return error(socket,'Somente o Host pode alterar o estado da sessão.');s.state=ensureState(m.payload?.state,s.sessionId,s.hostParticipantId);changed(s,'session.settings.changed',{state:s.state},c.participantId);break;
      case 'session.command':broadcast(s,'session.command',{command:m.payload?.command,fromParticipantId:c.participantId,data:m.payload?.data??null},c.participantId);break;
      default:error(socket,'Tipo de mensagem não suportado.');
    }
  });
  socket.on('close',()=>{const c=clients.get(socket);if(!c)return;clients.delete(socket);const s=sessions.get(c.sessionId);if(!s||s.clients.get(c.participantId)?.socket!==socket)return;s.clients.delete(c.participantId);const p=participant(s,c.participantId);if(p)p.online=false;changed(s,'participant.left',{participantId:c.participantId,participantCount:activeCount(s),online:false},c.participantId);if(c.participantId===s.hostParticipantId)broadcast(s,'host.disconnected',{participantId:c.participantId});if(!s.clients.size&&!s.cleanup)s.cleanup=setTimeout(()=>{if(!s.clients.size)sessions.delete(s.sessionId);},30*60*1000);});
});
console.log(`KaraokeAI signaling listening on ws://0.0.0.0:${port}`);
