import { randomUUID } from 'node:crypto';
import { WebSocketServer, WebSocket } from 'ws';

type Role = 'host' | 'participant' | 'tv';
type Client = { socket: WebSocket; sessionId: string; participantId: string; role: Role };
type Message = { type?: string; sessionId?: string; senderId?: string; payload?: any };
type Session = { id: string; hostId: string; state: any; clients: Map<string, Client>; sequence: number };
type EventType = 'participant.joined' | 'participant.left' | 'participant.updated' | 'host.changed' | 'queue.added' | 'queue.updated' | 'queue.removed' | 'queue.next' | 'singer.called' | 'performance.started' | 'performance.paused' | 'performance.resumed' | 'performance.finished' | 'performance.scored' | 'round.updated' | 'session.settings.changed';

const port = Number(process.env.PORT ?? 8787);
const defaultCapacity = clamp(Number(process.env.DEFAULT_SESSION_CAPACITY ?? 50), 2, 100);
const maxSongs = clamp(Number(process.env.MAX_SONGS_PER_PARTICIPANT ?? 3), 1, 20);
const legacySnapshots = process.env.LEGACY_SNAPSHOT_BROADCAST !== 'false';
const sessions = new Map<string, Session>();
const sockets = new Map<WebSocket, Client>();

function clamp(n: number, min: number, max: number) { return Number.isFinite(n) ? Math.max(min, Math.min(max, Math.floor(n))) : min; }
function id(v: unknown): v is string { return typeof v === 'string' && v.trim().length > 0 && v.length <= 128; }
function send(ws: WebSocket, type: string, payload: unknown) { if (ws.readyState === WebSocket.OPEN) ws.send(JSON.stringify({ id: randomUUID(), type, timestamp: Date.now(), payload })); }
function fail(ws: WebSocket, message: string) { send(ws, 'session.error', { message }); }
function person(s: Session, pid: string) { return s.state.participants.find((p: any) => p.id === pid); }
function active(s: Session) { return s.state.participants.filter((p: any) => p.role !== 'tv' && p.online !== false).length; }
function emit(s: Session, type: EventType, payload: unknown, actor?: string, audience?: string[]) { const event = { eventId: randomUUID(), sequence: ++s.sequence, sessionId: s.id, type, timestamp: Date.now(), ...(actor ? { actorParticipantId: actor } : {}), ...(audience ? { audience: { participantIds: audience } } : {}), payload }; for (const c of s.clients.values()) if (!audience || audience.includes(c.participantId)) send(c.socket, 'session.event', event); }
function broadcast(s: Session, type: string, payload: unknown, except?: string) { for (const c of s.clients.values()) if (c.participantId !== except) send(c.socket, type, payload); }
function changed(s: Session, type: EventType, payload: unknown, actor?: string, audience?: string[]) { s.state.queueSize = s.state.queue.length; emit(s, type, payload, actor, audience); if (legacySnapshots) broadcast(s, 'session.state', { state: s.state }); }
function initialState(state: any, sid: string, hostId: string) { const s = state && typeof state === 'object' ? state : {}; s.sessionId = sid; s.hostParticipantId = hostId; s.createdAt ??= Date.now(); s.maxParticipants = clamp(Number(s.maxParticipants ?? defaultCapacity), 2, 100); s.participants = Array.isArray(s.participants) ? s.participants : []; s.queue = Array.isArray(s.queue) ? s.queue : []; s.queueSize = s.queue.length; s.roundId ??= randomUUID(); s.roundMode ??= { kind: 'songs', songCount: 1 }; s.roundResultsByParticipant ??= {}; s.restartCreditsByParticipant ??= {}; s.autoAdvance ??= true; s.status ??= 'lobby'; return s; }
function restartCredits(mode: any) { if (mode?.kind === 'open') return 1; const n = clamp(Number(mode?.songCount ?? 1), 1, 100); return n <= 2 ? 1 : n <= 4 ? 2 : Math.max(1, Math.floor(n * 0.3)); }
function ensureCredits(s: Session, pid: string) { s.state.restartCreditsByParticipant[pid] ??= restartCredits(s.state.roundMode); }
function nextSong(s: Session) { if (s.state.queue.some((q: any) => q.status === 'playing')) return undefined; const candidates = s.state.queue.filter((q: any) => { if (q.status !== 'ready') return false; const p = person(s, q.ownerParticipantId); if (!p || p.online === false || p.role === 'tv') return false; const r = s.state.roundResultsByParticipant?.[q.ownerParticipantId]; return !(s.state.roundMode?.kind === 'songs' && r?.roundId === s.state.roundId && r.finished); }); candidates.sort((a: any, b: any) => { const ac = Number(s.state.roundResultsByParticipant?.[a.ownerParticipantId]?.completedSongs ?? 0); const bc = Number(s.state.roundResultsByParticipant?.[b.ownerParticipantId]?.completedSongs ?? 0); if (ac !== bc) return ac - bc; return Number(a.addedAt) - Number(b.addedAt); }); return candidates[0]; }
function startSong(s: Session, q: any) { const now = Date.now(); const pid = `${q.id}-${now}-${randomUUID().slice(0, 8)}`; s.state.queue = s.state.queue.map((x: any) => x.id === q.id ? { ...x, status: 'playing', playbackStartedAt: now, playbackPositionSeconds: 0, playbackState: 'playing', activePerformanceId: pid } : x); s.state.status = 'playing'; changed(s, 'queue.next', { queueEntryId: q.id, participantId: q.ownerParticipantId }, q.ownerParticipantId); emit(s, 'singer.called', { queueEntryId: q.id, participantId: q.ownerParticipantId }, q.ownerParticipantId); emit(s, 'performance.started', { queueEntryId: q.id, performanceId: pid }, q.ownerParticipantId, [q.ownerParticipantId, ...s.state.participants.filter((p: any) => p.role === 'tv').map((p: any) => p.id)]); }

const wss = new WebSocketServer({ port });
wss.on('connection', ws => {
  ws.on('message', raw => {
    let m: Message; try { m = JSON.parse(raw.toString()); } catch { fail(ws, 'Mensagem JSON inválida.'); return; }
    if (!id(m.sessionId) || !id(m.senderId)) { fail(ws, 'sessionId e senderId são obrigatórios.'); return; }
    if (m.type === 'session.create') {
      if (sessions.has(m.sessionId)) return fail(ws, 'A sessão já existe.');
      const state = initialState(m.payload?.state, m.sessionId, m.senderId); let host = person({ state } as Session, m.senderId); if (host) { host.role = 'host'; host.online = true; } else state.participants.unshift({ id: m.senderId, name: String(m.payload?.name ?? 'Host').slice(0, 30), role: 'host', joinedAt: Date.now(), capabilities: m.payload?.capabilities ?? {}, online: true });
      state.restartCreditsByParticipant[m.senderId] ??= restartCredits(state.roundMode);
      const s: Session = { id: m.sessionId, hostId: m.senderId, state, clients: new Map(), sequence: 0 }; const c: Client = { socket: ws, sessionId: s.id, participantId: m.senderId, role: 'host' }; s.clients.set(c.participantId, c); sockets.set(ws, c); sessions.set(s.id, s); return send(ws, 'session.created', { sessionId: s.id, hostParticipantId: s.hostId, state: s.state });
    }
    const c = sockets.get(ws); const s = sessions.get(m.sessionId);
    if (m.type === 'session.join') {
      if (!s) return fail(ws, 'Sessão não encontrada.'); const role: Role = m.payload?.role === 'tv' ? 'tv' : 'participant'; if (role !== 'tv' && active(s) >= s.state.maxParticipants) return fail(ws, 'A sessão atingiu a capacidade de participantes.'); if (s.clients.has(m.senderId)) return fail(ws, 'Este participante já está conectado.'); let p = person(s, m.senderId); if (p && p.online !== false) return fail(ws, 'Este participante já está ativo nesta sessão.'); if (p) { p.online = true; p.role = role; } else { p = { id: m.senderId, name: String(m.payload?.name ?? 'Participante').slice(0, 30), role, joinedAt: Date.now(), capabilities: m.payload?.capabilities ?? {}, online: true }; s.state.participants.push(p); } if (role !== 'tv') ensureCredits(s, m.senderId); const nc: Client = { socket: ws, sessionId: s.id, participantId: m.senderId, role }; s.clients.set(nc.participantId, nc); sockets.set(ws, nc); changed(s, 'participant.joined', { participant: p, participantCount: active(s) }, m.senderId); return send(ws, 'session.joined', { sessionId: s.id, hostParticipantId: s.hostId, state: s.state });
    }
    if (m.type === 'session.reconnect') {
      if (!s) return fail(ws, 'Sessão não encontrada.'); const p = person(s, m.senderId); if (!p) return fail(ws, 'Participante não encontrado.'); const old = s.clients.get(m.senderId); if (old) { try { old.socket.close(); } catch {} } p.online = true; const nc: Client = { socket: ws, sessionId: s.id, participantId: m.senderId, role: p.role }; s.clients.set(m.senderId, nc); sockets.set(ws, nc); send(ws, 'session.reconnected', { sessionId: s.id, hostParticipantId: s.hostId, state: s.state }); return emit(s, 'participant.updated', { participant: p }, m.senderId);
    }
    if (!c || !s || c.sessionId !== s.id) return fail(ws, 'Conecte-se a uma sessão primeiro.');
    switch (m.type) {
      case 'queue.add': {
        if (c.role === 'tv') return fail(ws, 'A TV não pode adicionar músicas.'); const count = s.state.queue.filter((q: any) => q.ownerParticipantId === c.participantId && !['completed', 'cancelled'].includes(q.status)).length; if (count >= maxSongs) return fail(ws, `Você atingiu o limite de ${maxSongs} músicas na fila.`); const title = String(m.payload?.title ?? '').trim().slice(0, 160); if (!title) return fail(ws, 'O título da música é obrigatório.'); const q = { id: randomUUID(), ownerParticipantId: c.participantId, title, artist: String(m.payload?.artist ?? '').trim().slice(0, 120) || undefined, sourceId: String(m.payload?.sourceId ?? '').trim().slice(0, 200) || undefined, requestedKey: String(m.payload?.requestedKey ?? '').trim().slice(0, 16) || undefined, roundId: s.state.roundId, addedAt: Date.now(), status: 'queued' }; s.state.queue.push(q); changed(s, 'queue.added', { entry: q }, c.participantId); break;
      }
      case 'queue.remove': { const q = s.state.queue.find((x: any) => x.id === String(m.payload?.queueEntryId ?? '')); if (!q) return fail(ws, 'Música não encontrada.'); if (c.participantId !== s.hostId && q.ownerParticipantId !== c.participantId) return fail(ws, 'Você só pode remover suas próprias músicas.'); if (q.status === 'playing') return fail(ws, 'A música está em reprodução.'); s.state.queue = s.state.queue.filter((x: any) => x.id !== q.id); changed(s, 'queue.removed', { queueEntryId: q.id }, c.participantId); break; }
      case 'queue.status.set': { const q = s.state.queue.find((x: any) => x.id === String(m.payload?.queueEntryId ?? '')); const status = String(m.payload?.status ?? ''); if (!q) return fail(ws, 'Música não encontrada.'); if (!['queued', 'preparing', 'ready', 'playing', 'completed', 'cancelled'].includes(status)) return fail(ws, 'Status inválido.'); if (c.participantId !== s.hostId && q.ownerParticipantId !== c.participantId) return fail(ws, 'Sem permissão para alterar esta música.'); if (status === 'playing') { if (s.state.queue.some((x: any) => x.status === 'playing' && x.id !== q.id)) return fail(ws, 'Já existe uma música em reprodução.'); startSong(s, q); } else { const updated = { ...q, status, ...(m.payload?.assetId ? { assetId: String(m.payload.assetId) } : {}), ...(m.payload?.manifestUrl ? { manifestUrl: String(m.payload.manifestUrl) } : {}), ...(m.payload?.selectedKey ? { selectedKey: String(m.payload.selectedKey) } : {}), ...(Number.isFinite(m.payload?.preparationProgress) ? { preparationProgress: clamp(Number(m.payload.preparationProgress), 0, 100) } : {}) }; s.state.queue = s.state.queue.map((x: any) => x.id === q.id ? updated : x); changed(s, 'queue.updated', { entry: updated, queueEntryId: q.id }, c.participantId); } break; }
      case 'queue.next': { if (c.participantId !== s.hostId) return fail(ws, 'Somente o Host pode avançar a fila.'); const q = nextSong(s); if (!q) return fail(ws, 'Não há música pronta para o próximo cantor.'); startSong(s, q); break; }
      case 'playback.finished': { if (c.role !== 'tv') return fail(ws, 'Somente a TV pode finalizar a reprodução.'); const q = s.state.queue.find((x: any) => x.id === String(m.payload?.queueEntryId ?? '')); if (!q || q.status !== 'playing') return fail(ws, 'Apresentação não encontrada.'); q.status = 'completed'; q.playbackState = undefined; s.state.status = 'lobby'; changed(s, 'performance.finished', { queueEntryId: q.id }); if (s.state.autoAdvance !== false) { const next = nextSong(s); if (next) startSong(s, next); } break; }
      case 'performance.complete': { const q = s.state.queue.find((x: any) => x.id === String(m.payload?.queueEntryId ?? '')); if (!q || q.ownerParticipantId !== c.participantId || q.status !== 'completed') return fail(ws, 'A apresentação não pode receber esta pontuação.'); const raw = m.payload?.score ?? {}; const score = { overall: clamp(Number(raw.overall), 0, 100), pitch: clamp(Number(raw.pitch), 0, 100), precision: clamp(Number(raw.precision), 0, 100), rhythm: clamp(Number(raw.rhythm), 0, 100), stability: clamp(Number(raw.stability), 0, 100), matchedSamples: Math.max(0, Math.floor(Number(raw.matchedSamples ?? 0))) }; q.score = score; const rows = s.state.queue.filter((x: any) => x.ownerParticipantId === q.ownerParticipantId && x.roundId === s.state.roundId && x.status === 'completed' && x.score); const required = s.state.roundMode?.kind === 'songs' ? Number(s.state.roundMode.songCount) : undefined; s.state.roundResultsByParticipant[q.ownerParticipantId] = { roundId: s.state.roundId, completedSongs: rows.length, ...(required ? { requiredSongs: required } : {}), score: rows.length ? Math.round(rows.reduce((a: number, x: any) => a + x.score.overall, 0) / rows.length) : 0, finished: required ? rows.length >= required : false, updatedAt: Date.now(), songScores: rows.map((x: any) => ({ queueEntryId: x.id, score: x.score.overall })) }; changed(s, 'performance.scored', { queueEntryId: q.id, score }, c.participantId); break; }
      case 'session.settings.set': { if (c.participantId !== s.hostId) return fail(ws, 'Somente o Host pode alterar configurações.'); const next = m.payload?.maxParticipants === undefined ? s.state.maxParticipants : clamp(Number(m.payload.maxParticipants), 2, 100); if (next < active(s)) return fail(ws, 'A capacidade não pode ser menor que os participantes atuais.'); s.state.maxParticipants = next; if (typeof m.payload?.autoAdvance === 'boolean') s.state.autoAdvance = m.payload.autoAdvance; changed(s, 'session.settings.changed', { state: { maxParticipants: next, autoAdvance: s.state.autoAdvance } }, c.participantId); break; }
      case 'session.state.set': { if (c.participantId !== s.hostId) return fail(ws, 'Somente o Host pode alterar o estado.'); s.state = initialState(m.payload?.state, s.id, s.hostId); changed(s, 'session.settings.changed', { state: s.state }, c.participantId); break; }
      case 'host.transfer': { if (c.participantId !== s.hostId) return fail(ws, 'Somente o Host pode transferir a função.'); const targetId = String(m.payload?.targetParticipantId ?? ''); const target = person(s, targetId); if (!target || target.role === 'tv' || target.online === false) return fail(ws, 'Participante inválido para Host.'); const previous = s.hostId; s.hostId = targetId; s.state.hostParticipantId = targetId; s.state.participants = s.state.participants.map((p: any) => p.id === previous ? { ...p, role: 'participant' } : p.id === targetId ? { ...p, role: 'host' } : p); const old = s.clients.get(previous); const tc = s.clients.get(targetId); if (old) old.role = 'participant'; if (tc) tc.role = 'host'; changed(s, 'host.changed', { previousHostParticipantId: previous, hostParticipantId: targetId }, c.participantId); break; }
      default: fail(ws, 'Tipo de mensagem não suportado.');
    }
  });
  ws.on('close', () => { const c = sockets.get(ws); if (!c) return; sockets.delete(ws); const s = sessions.get(c.sessionId); if (!s || s.clients.get(c.participantId)?.socket !== ws) return; s.clients.delete(c.participantId); const p = person(s, c.participantId); if (p) p.online = false; changed(s, 'participant.left', { participantId: c.participantId, participantCount: active(s), online: false }, c.participantId); if (c.participantId === s.hostId) broadcast(s, 'host.disconnected', { participantId: c.participantId }); });
});

console.log(`KaraokeAI signaling listening on ws://0.0.0.0:${port}`);
